import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import './AnalysisDetail.css';

export default function AnalysisDetail({ apiBase }) {
  const { matchId } = useParams(); const navigate = useNavigate(); const [detail, setDetail] = useState(null); const [error, setError] = useState('');
  useEffect(() => { (async () => { try { const res = await fetch(`${apiBase}/api/users/matches/${matchId}`, { headers: { Authorization: `Bearer ${localStorage.getItem('token')}` } }); const data = await res.json(); if (!res.ok) throw new Error(data.message); setDetail(data); } catch (err) { setError(err.message || 'Could not load this analysis'); } })(); }, [matchId, apiBase]);
  if (error) return <div className="analysis-detail-empty"><h3>{error}</h3><button className="btn btn-primary" onClick={() => navigate('/')}>Back to dashboard</button></div>;
  if (!detail) return <div className="analysis-detail-empty">Loading analysis…</div>;
  return <section className="analysis-detail"><button className="btn btn-ghost" onClick={() => navigate('/')}>← Dashboard</button><div className="detail-heading"><div><p className="detail-kicker">Saved CV Analysis</p><h2>{detail.job?.title || 'Job analysis'}</h2><p>{detail.job?.company || 'Career Craft'} · {detail.job?.location || 'Location not specified'}</p></div><div className="detail-score">{detail.matchScore}%<small>Match</small></div></div><div className="detail-grid"><article className="detail-card"><h3>Skills you have</h3><div className="detail-tags">{detail.matchingSkills.map(skill => <span className="detail-tag success" key={skill}>{skill}</span>) || 'None'}</div></article><article className="detail-card"><h3>Skill gaps</h3><div className="detail-tags">{detail.missingSkills.length ? detail.missingSkills.map(skill => <span className="detail-tag missing" key={skill}>{skill}</span>) : <span>All detected skills match.</span>}</div></article></div><article className="detail-card"><h3>Your CV</h3><p>{detail.cv?.originalName || detail.cv?.filename || 'Saved CV'}</p><div className="detail-tags">{(detail.cv?.skills || []).map(skill => <span className="detail-tag" key={skill}>{skill}</span>)}</div></article><article className="detail-card"><h3>Job description</h3><p className="detail-description">{detail.job?.description || 'The saved job description is not available for this analysis.'}</p>{detail.job?.jobUrl && <a className="btn btn-primary" href={detail.job.jobUrl} target="_blank" rel="noreferrer">View job posting</a>}</article></section>;
}
